### ISSUE TITLE
Does this reset the map to the center?

### ISSUE THREAD

**Issue by FunkyLoveCow** [alanshaw/leaflet-zoom-min#3]
As the title says, does is this supposed to reset the map to the `center` as well as the zoom level?

From the example in the `README`, this is specified

```
center: [51.505, -0.09],
```

When pressing the world button, it doesn't appear to recenter on that point. Instead it zooms back out based on the current center point. Is this the expected behavior?

**Comment by alanshaw** [comment]
Yes, that's the expected behaviour.

**Comment by dnsBlah** [comment]
Just append an ; on line 39: this._map.setZoom(this._map.getMinZoom())
And add a new line 40 with : this._map.panTo(new L.LatLng(55, 0)); //Or whatever center point, not sure how to get center point from the map object
